name: api_client_cache
description: A simple HTTP cache for api_client
version: 1.0.0
author: Lucas <me@dotronglong.com>
homepage: https://github.com/dotronglong/dart-api-client-cache

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  api_client: ^2.2.0
  crypto: ^2.1.3
dev_dependencies:
  test: ^1.3.4
  mockito: ^4.0.0
  coveralls: ^5.1.0
